name: CloudSync-Actions

on:
  push:
    branches:
      - master
  watch:
    types: started
    
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: CloudSync-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Get rclone config from GitHub secret
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: echo "$RCLONE_CONFIG" > rclone.conf

      - name: Write rclone config to file
        run: |
          mkdir -p ~/.config/rclone
          mv rclone.conf ~/.config/rclone/rclone.conf


      - name: Read rclone config file
        run: |
          RCLONE_CONFIG=$(cat ~/.config/rclone/rclone.conf)

      - name: Set rclone config as GitHub secret
        env:
          CLI_TOKEN: ${{ secrets.CLI_TOKEN }}
        run: |
         echo ${CLI_TOKEN} > token
         gh auth login --with-token < token
         gh secret set RCLONE_CONFIG --repo wekingchen/Rclone-Actions-new --body "$RCLONE_CONFIG"
