name: PanSync-Actions

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */6 * * *

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: PanSync-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Read Rclone config from GitHub secret
        env:
          RCLONE_CONFIG: ${{ secrets.PANSYNC_RCLONE_CONFIG }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

      - name: Download alist directory
        run: |
          mkdir -p ~/alist
          rclone copy weking_dropbox:PrivateDoc/rclone/PanSync/alist ~/alist
          echo "已下载alist文件夹到本地~/alist"

      - name: Run alist container
        run: |
          docker run -d --restart=unless-stopped -v ~/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest
          echo "alist容器已启动"
          
      - name: Rclone-Run
        run: |
          # Rclone-Run
          # 延迟函数
          delay()
          {
          random_time=$(($RANDOM % $1))
          echo "等待 ${random_time} 分钟后开始同步"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          }
          # 随机延迟0~15分钟后再进行操作,可自行设置时间
          delay 1
          
          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          
          rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/24.108.0528.0005" -v pan: scut_s:/media
          echo "华工SharePoint影视文件同步完毕"
          
          rclone lsd scut_o:
          echo "华工OneDrive保活刷新完毕"

          rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/24.108.0528.0005" -v pan: chunker:
          echo "陕科大rclone聚合影视文件同步完毕"
          
          rclone sync -v pan: pikpak:Video
          #rclone copy -v pikpak:"My Pack/巡回检察组.2020.EP01-43.HD1080P.X264.AAC.Mandarin.CHS.BDE4" pan:ping
          echo "pikpak影视文件同步完毕"

          #rclone sync -v pan: quark:
          #echo "夸克网盘影视文件同步完毕"
          
          rclone copy ~/.config/rclone weking_dropbox:PrivateDoc/rclone/PanSync
          echo "rclone配置档备份完毕"
          
      - name: Stop alist container
        run: |
          docker stop alist
          docker rm alist
          echo "alist容器已停止并删除"

      - name: Upload alist directory back to Dropbox
        run: |
          rclone sync ~/alist weking_dropbox:PrivateDoc/rclone/PanSync/alist
          echo "已将~/alist文件夹上传回Dropbox"

      - name: Write Rclone config to GitHub secret
        env:
          CLI_TOKEN: ${{ secrets.CLI_TOKEN }}
          REPO: wekingchen/Rclone-Actions
        run: |
          RCLONE_CONFIG=$(cat ~/.config/rclone/rclone.conf)
          gh auth login --with-token <<< "${CLI_TOKEN}"
          gh secret set PANSYNC_RCLONE_CONFIG -b"${RCLONE_CONFIG}" --repo "${REPO}"

      - name: Delete workflow runs
        uses: wekingchen/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 550
